/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package panel.options;

import javax.swing.JPanel;

/**
 *
 * @author legranma
 */
public class panelCompletion extends Param {

    @Override
    public JPanel personliserParams() {
        setTitle("Paramètres de complétion");
        return new ParamsCompletion();
    }

    public class ParamsCompletion extends javax.swing.JPanel {

        /**
         * Creates new form panelCompletion
         */
        public ParamsCompletion() {
            initComponents();
        }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        chk_frappe = new javax.swing.JCheckBox();
        chk_ortho = new javax.swing.JCheckBox();
        chk_morph = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        chk_espace = new javax.swing.JCheckBox();
        chk_maj = new javax.swing.JCheckBox();
        chk_accent = new javax.swing.JCheckBox();

        jLabel1.setText("Correction de fautes");

        chk_frappe.setText("Frappes");
        chk_frappe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_frappeActionPerformed(evt);
            }
        });

        chk_ortho.setText("Orthographe");

        chk_morph.setText("Morphologie");

        jLabel2.setText("Générations automatiques");

        chk_espace.setText("Espaces");
        chk_espace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_espaceActionPerformed(evt);
            }
        });

        chk_maj.setText("Majuscules");

        chk_accent.setText("Accents");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chk_espace)
                        .addGap(18, 18, 18)
                        .addComponent(chk_maj)
                        .addGap(18, 18, 18)
                        .addComponent(chk_accent))
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chk_frappe)
                        .addGap(18, 18, 18)
                        .addComponent(chk_ortho)
                        .addGap(18, 18, 18)
                        .addComponent(chk_morph))
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chk_frappe)
                    .addComponent(chk_ortho)
                    .addComponent(chk_morph))
                .addGap(59, 59, 59)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chk_espace)
                    .addComponent(chk_maj)
                    .addComponent(chk_accent))
                .addContainerGap(99, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void chk_frappeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_frappeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chk_frappeActionPerformed

    private void chk_espaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_espaceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chk_espaceActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chk_accent;
    private javax.swing.JCheckBox chk_espace;
    private javax.swing.JCheckBox chk_frappe;
    private javax.swing.JCheckBox chk_maj;
    private javax.swing.JCheckBox chk_morph;
    private javax.swing.JCheckBox chk_ortho;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
    }
}