/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package panel.options;

import javax.swing.JPanel;
import panel.options.hand.design.AbstractSpecificPanel;

/**
 *
 * @author legranma
 */
public class PanelGeneral extends AbstractSpecificPanel {

    public PanelGeneral(String title) {
        super(title);
    }

    @Override
    protected JPanel generateSpecificPanel() {
        return new ParamsGeneral();
    }

    public class ParamsGeneral extends javax.swing.JPanel {

        /**
         * Creates new form panelGeneral
         */
        public ParamsGeneral() {
            initComponents();
        }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chk_demarrage = new javax.swing.JCheckBox();
        cmb_profilDefaut = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        chk_afficheBarre = new javax.swing.JCheckBox();

        chk_demarrage.setText("Lancement au démarrage de VITIPI");

        cmb_profilDefaut.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Défaut", "Item 2", "Item 3", "Item 4" }));
        cmb_profilDefaut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_profilDefautActionPerformed(evt);
            }
        });

        jLabel1.setText("Profil par défaut :");

        chk_afficheBarre.setText("Afficher la barre d'outils");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chk_afficheBarre)
                    .addComponent(chk_demarrage)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(cmb_profilDefaut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(190, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(chk_demarrage)
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_profilDefaut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(chk_afficheBarre)
                .addGap(64, 64, 64))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmb_profilDefautActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_profilDefautActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_profilDefautActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chk_afficheBarre;
    private javax.swing.JCheckBox chk_demarrage;
    private javax.swing.JComboBox cmb_profilDefaut;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
    }
}